name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:

    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2.3.1
      with:
        lfs: true

    # Cache
    - uses: actions/cache@v2.0.0
      with:
        path: ${{ matrix.projectPath }}/Library
        key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-${{ matrix.projectPath }}-
          Library-

    # Build
    - name: Build project
      uses: webbertakken/unity-builder@v1.0
      with:
        unityVersion: 2019.4.0f1
        targetPlatform: StandaloneWindows 

    # Output 
    - uses: actions/upload-artifact@v1
      with:
        name: Build
        path: build
